### ISSUE TITLE
Use LTS Java Runtime for Releases

### ISSUE THREAD

**Issue by DatL4g** [dzirbel/compose-material-context-menu#1]
Please use Long-Term-Support versions of the Java Runtime to compile releases.
The current release (`0.1.0`) uses Java version 18, so applications have to rely on **at least** that version or higher, however there is currently no newer LTS release, which may break stuff in some development environments

https://endoflife.date/java

**Comment by dzirbel** [comment]
Good call, I hadn't given this much thought before. I've built a new release 0.1.1 with Java 11 which I'll use going forward.
