### ISSUE TITLE
Text in Context-Menu does not apply specified color

### ISSUE THREAD

**Issue by DatL4g** [dzirbel/compose-material-context-menu#2]
The text in the context menu is always black, whether or not the theme is light/dark or if a completly different color is set.
The icon however is styled correctly

![Bildschirmfoto vom 2023-08-15 13-47-42](https://github.com/dzirbel/compose-material-context-menu/assets/46448715/e3af2d72-c875-45ba-92e3-f42821d32f78)

```kotlin
val contextMenuStyling = ContextMenuColors(
	surface = MaterialTheme.colorScheme.surface,
	text = Color.Red,
	icon = MaterialTheme.colorScheme.onSurface,
	divider = MaterialTheme.colorScheme.onSurfaceVariant
)
```

```kotlin
CompositionLocalProvider(
	LocalContextMenuRepresentation provides MaterialContextMenuRepresentation(colors = contextMenuStyling),
	LocalTextContextMenu provides MaterialTextContextMenu,
	LocalScaling provides windowScaling()
) {
	content()
}
```

**Comment by dzirbel** [comment]
Nice catch; I had forgotten to apply this color to the various `Text()`s, which were defaulting to the local Material `onSurface` color instead. This should be fixed in 0.1.1.
